# Compose file for production.

volumes:
  db_data:
  storage:

services:
  app:
    image: snipe/snipe-it:v8.0.4
    restart: unless-stopped
    volumes:
      - storage:/var/lib/snipeit
    ports:
      - 8000:80
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file: 
      - .env

  db:
    image: mariadb:11.5.2
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: snipeit
      MYSQL_USER: snipeit
      MYSQL_PASSWORD: ele795
      MYSQL_ROOT_PASSWORD: ele795
    healthcheck:
      # https://mariadb.com/kb/en/using-healthcheck-sh/#compose-file-example
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 1s
      retries: 5
